var IDENTITY_DEPARTMENT_ENUM = {
      NONE                                            : "",
      JUSTICE_SAFETY_OFFICE                           : "SSP-SECRET.SEGURANCA PUBLICA",
      PUBLIC_SAFETY_OFFICE                            : "SECRETARIA DA JUSTICA E SEGURANCA",
      AERONAUTICS_MINISTRY                            : "MINISTERIO DA AERONAUTICA",
      ARMY_MINISTRY                                   : "MINISTERIO DO EXERCITO",
      NAVY_MINISTRY                                   : "MINISTERIO DA MARINHA",
      FEDERAL_POLICE                                  : "POLICIA FEDERAL",
      CLASS_IDENTITY_CARD                             : "CARTEIRA DE IDENTID. CLASSISTA",
      ADMINISTRATION_REGIONAL_COUNCIL                 : "CONS.REG.DE ADMINISTRACAO",
      SOCIAL_ASSITENT_REGIONAL_COUNCIL                : "CONS.REG.DE ASSIST.SOCIAIS",
      BIBLIOTHECONOMY_REGIONAL_COUNCIL                : "CONS.REG.DE BIBLIOTECONOMIA",
      ACCOUNTANCY_REGIONAL_COUNCIL                    : "CONS.REG.DE CONTABILIDADE",
      REALTOR_REGIONAL_COUNCIL                        : "CONS.REG.CORRETORES IMOVEIS",
      NURSING_REGIONAL_COUNCIL                        : "CONS.REG.ENFERMAGEM",
      AGRONOMY_ARCHITECT_ENGINEERING_REGIONAL_COUNCIL : "CONS.REG.ENG.ARQ. E AGRONOMIA",
      STATISTICS_REGIONAL_COUNCIL                     : "CONS.REG.DE ESTATISTICA",
      PHARMACY_REGIONAL_COUNCIL                       : "CONS.REG.DE FARMACIA",
      PHYSIOTHERAPY_OCCUPATIONAL_REGIONAL_COUNCIL     : "CONS.REG.FISIOT.TERAPIA OCUP.",
      MEDICINE_REGIONAL_COUNCIL                       : "CONS.REG.DE MEDICINA",
      VETERINARY_REGIONAL_COUNCIL                     : "CONS.REG.MEDICINA VETERINARIA",
      NUTRITION_REGIONAL_COUNCIL                      : "CONS.REG.DE NUTRICAO",
      DENTISTRY_REGIONAL_COUNCIL                      : "CONS.REG.DE ODONTOLOGIA",
      PUBLIC_RELATIONS_REGIONAL_COUNCIL               : "CONS.REG.PROF.RELACOES PUBLIC.",
      PSYCHOLOGY_REGIONAL_COUNCIL                     : "CONS.REG.DE PSICOLOGIA",
      CHEMISTRY_REGIONAL_COUNCIL                      : "CONS.REG.DE QUIMICA",
      COMMERCIAL_REPRESENTATIONS_REGIONAL_COUNCIL     : "CONS.REG.REPRES.COMERCIAIS",
      BRAZILIAN_MUSICIAN_ASSOCIATION                  : "ORDEM DOS MUSICOS DO BRASIL",
      BRAZILIAN_LAWYER_ASSOCIATION                    : "ORDEM DOS ADVOGADOS DO BRASIL",
      OTHER_EMMITERS                                  : "OUTROS EMISSORES",
      FOREIGN_DOCUMENT                                : "DOCUMENTOS ESTRANGEIROS"
};

/* ENUMERATION_VALUES */
IDENTITY_DEPARTMENT_ENUM.ENUMERATION_VALUES = [
      {data: IDENTITY_DEPARTMENT_ENUM.NONE                                            , label:""},
      {data: IDENTITY_DEPARTMENT_ENUM.JUSTICE_SAFETY_OFFICE                           , label:"SSP-SECRET.SEGURANCA PUBLICA  "},    
      {data: IDENTITY_DEPARTMENT_ENUM.PUBLIC_SAFETY_OFFICE                            , label:"SECRETARIA DA JUSTICA E SEGURANCA"},     
      {data: IDENTITY_DEPARTMENT_ENUM.AERONAUTICS_MINISTRY                            , label:"MINISTERIO DA AERONAUTICA     "},      
      {data: IDENTITY_DEPARTMENT_ENUM.ARMY_MINISTRY                                   , label:"MINISTERIO DO EXERCITO        "},      
      {data: IDENTITY_DEPARTMENT_ENUM.NAVY_MINISTRY                                   , label:"MINISTERIO DA MARINHA         "},      
      {data: IDENTITY_DEPARTMENT_ENUM.FEDERAL_POLICE                                  , label:"POLICIA FEDERAL               "},      
      {data: IDENTITY_DEPARTMENT_ENUM.CLASS_IDENTITY_CARD                             , label:"CARTEIRA DE IDENTID. CLASSISTA"},      
      {data: IDENTITY_DEPARTMENT_ENUM.ADMINISTRATION_REGIONAL_COUNCIL                 , label:"CONS.REG.DE ADMINISTRACAO     "},      
      {data: IDENTITY_DEPARTMENT_ENUM.SOCIAL_ASSITENT_REGIONAL_COUNCIL                , label:"CONS.REG.DE ASSIST.SOCIAIS    "},      
      {data: IDENTITY_DEPARTMENT_ENUM.BIBLIOTHECONOMY_REGIONAL_COUNCIL                , label:"CONS.REG.DE BIBLIOTECONOMIA   "},      
      {data: IDENTITY_DEPARTMENT_ENUM.ACCOUNTANCY_REGIONAL_COUNCIL                    , label:"CONS.REG.DE CONTABILIDADE     "},      
      {data: IDENTITY_DEPARTMENT_ENUM.REALTOR_REGIONAL_COUNCIL                        , label:"CONS.REG.CORRETORES IMOVEIS   "},      
      {data: IDENTITY_DEPARTMENT_ENUM.NURSING_REGIONAL_COUNCIL                        , label:"CONS.REG.ENFERMAGEM           "},      
      {data: IDENTITY_DEPARTMENT_ENUM.AGRONOMY_ARCHITECT_ENGINEERING_REGIONAL_COUNCIL , label:"CONS.REG.ENG.ARQ. E AGRONOMIA "},      
      {data: IDENTITY_DEPARTMENT_ENUM.STATISTICS_REGIONAL_COUNCIL                     , label:"CONS.REG.DE ESTATISTICA       "},      
      {data: IDENTITY_DEPARTMENT_ENUM.PHARMACY_REGIONAL_COUNCIL                       , label:"CONS.REG.DE FARMACIA          "},      
      {data: IDENTITY_DEPARTMENT_ENUM.PHYSIOTHERAPY_OCCUPATIONAL_REGIONAL_COUNCIL     , label:"CONS.REG.FISIOT.TERAPIA OCUP. "},      
      {data: IDENTITY_DEPARTMENT_ENUM.MEDICINE_REGIONAL_COUNCIL                       , label:"CONS.REG.DE MEDICINA          "},      
      {data: IDENTITY_DEPARTMENT_ENUM.VETERINARY_REGIONAL_COUNCIL                     , label:"CONS.REG.MEDICINA VETERINARIA "},      
      {data: IDENTITY_DEPARTMENT_ENUM.NUTRITION_REGIONAL_COUNCIL                      , label:"CONS.REG.DE NUTRICAO          "},      
      {data: IDENTITY_DEPARTMENT_ENUM.DENTISTRY_REGIONAL_COUNCIL                      , label:"CONS.REG.DE ODONTOLOGIA       "},      
      {data: IDENTITY_DEPARTMENT_ENUM.PUBLIC_RELATIONS_REGIONAL_COUNCIL               , label:"CONS.REG.PROF.RELACOES PUBLIC."},      
      {data: IDENTITY_DEPARTMENT_ENUM.PSYCHOLOGY_REGIONAL_COUNCIL                     , label:"CONS.REG.DE PSICOLOGIA        "},      
      {data: IDENTITY_DEPARTMENT_ENUM.CHEMISTRY_REGIONAL_COUNCIL                      , label:"CONS.REG.DE QUIMICA           "},      
      {data: IDENTITY_DEPARTMENT_ENUM.COMMERCIAL_REPRESENTATIONS_REGIONAL_COUNCIL     , label:"CONS.REG.REPRES.COMERCIAIS    "},      
      {data: IDENTITY_DEPARTMENT_ENUM.BRAZILIAN_MUSICIAN_ASSOCIATION                  , label:"ORDEM DOS MUSICOS DO BRASIL   "},      
      {data: IDENTITY_DEPARTMENT_ENUM.BRAZILIAN_LAWYER_ASSOCIATION                    , label:"ORDEM DOS ADVOGADOS DO BRASIL "},      
      {data: IDENTITY_DEPARTMENT_ENUM.OTHER_EMMITERS                                  , label:"OUTROS EMISSORES              "},      
      {data: IDENTITY_DEPARTMENT_ENUM.FOREIGN_DOCUMENT                                , label:"DOCUMENTOS ESTRANGEIROS       "}];

//extende AbstractEnumeration para obter algumas funcoes genericas, como getLabelByKey e getIndexByKey
define(['/dts/hgp/html/js/global/enumeration/AbstractEnumeration.js'],function(){
   $.extend( IDENTITY_DEPARTMENT_ENUM, AbstractEnumeration );
});